"""
Generates a downloadable PDF relationship brief for a contact, using the
same data as the AI Brief endpoint (relationship_summary, things_to_remember,
open_loops, conversation_starters, suggested_actions) plus basic contact info
and meeting history.
"""

import io
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, ListFlowable, ListItem, HRFlowable,
)


def _bullets(items, style):
    if not items:
        return Paragraph("<i>None recorded.</i>", style)
    return ListFlowable(
        [ListItem(Paragraph(str(i), style)) for i in items],
        bulletType="bullet",
        leftIndent=14,
    )


def build_contact_brief_pdf(contact: dict, brief: dict, meetings: list[dict]) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=letter,
        topMargin=0.75 * inch, bottomMargin=0.75 * inch,
        leftMargin=0.75 * inch, rightMargin=0.75 * inch,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "BriefTitle", parent=styles["Title"], textColor=colors.HexColor("#2b2320"),
    )
    subtitle_style = ParagraphStyle(
        "BriefSubtitle", parent=styles["Normal"], textColor=colors.HexColor("#7a6f68"),
        fontSize=11, spaceAfter=14,
    )
    heading_style = ParagraphStyle(
        "SectionHeading", parent=styles["Heading2"],
        textColor=colors.HexColor("#a8623f"), spaceBefore=16, spaceAfter=6,
    )
    body_style = ParagraphStyle(
        "Body", parent=styles["Normal"], fontSize=10.5, leading=15,
    )

    story = []
    name = contact.get("name", "Contact")
    role = contact.get("role") or ""
    company = contact.get("company") or ""
    subtitle_bits = [b for b in [role, f"at {company}" if company else ""] if b]

    story.append(Paragraph(f"Relationship Brief: {name}", title_style))
    if subtitle_bits:
        story.append(Paragraph(" ".join(subtitle_bits), subtitle_style))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#e5ded8")))

    story.append(Paragraph("Relationship Summary", heading_style))
    story.append(Paragraph(brief.get("relationship_summary", "No summary available."), body_style))

    story.append(Paragraph("Things to Remember", heading_style))
    story.append(_bullets(brief.get("things_to_remember", []), body_style))

    story.append(Paragraph("Open Loops", heading_style))
    story.append(_bullets(brief.get("open_loops", []), body_style))

    story.append(Paragraph("Conversation Starters", heading_style))
    story.append(_bullets(brief.get("conversation_starters", []), body_style))

    story.append(Paragraph("Suggested Actions", heading_style))
    story.append(_bullets(brief.get("suggested_actions", []), body_style))

    if meetings:
        story.append(Paragraph("Meeting History", heading_style))
        for m in sorted(meetings, key=lambda x: x.get("date", ""), reverse=True)[:10]:
            date = m.get("date", "")
            summary = m.get("summary", "")
            story.append(Paragraph(f"<b>{date}</b> — {summary}", body_style))
            story.append(Spacer(1, 4))

    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#e5ded8")))
    story.append(Paragraph(
        "Generated by MeetMind AI", ParagraphStyle(
            "Footer", parent=styles["Normal"], fontSize=8,
            textColor=colors.HexColor("#a89e97"), spaceBefore=8,
        )
    ))

    doc.build(story)
    return buffer.getvalue()